export type CustomerTier = "vip" | "gold" | "member" | "black";

export interface CustomerRecord {
  id: string;
  customerCode?: string;
  name: string;
  initials: string;
  phone: string;
  email: string;
  gender?: string;
  dateOfBirth?: string;
  tier: CustomerTier;
  payLater?: string;
  payLaterLimit?: string;
  joinedDate?: string;
  tags?: string[];
  status?: "active" | "inactive";
  visits: number;
  points: number;
  lifetimeSpend: string;
  lastVisit: string;
  memberSince: string;
  favorite: string;
}

const diceBearAvatarUrl = "https://api.dicebear.com/10.x/open-peeps/svg";

export function getCustomerAvatarUrl(seed: string) {
  return `${diceBearAvatarUrl}?seed=${encodeURIComponent(seed)}`;
}

export const customerRecords: CustomerRecord[] = [
  {
    id: "mads-mikkelsen",
    customerCode: "C001",
    name: "Mads Mikkelsen",
    initials: "MM",
    phone: "092 888 888",
    email: "mads_mikkelsen@gmail.com",
    gender: "Male",
    dateOfBirth: "01/02/1960",
    tier: "black",
    payLater: "$5.00",
    payLaterLimit: "$50.00",
    joinedDate: "20/06/2024",
    tags: ["Staff", "Black Member"],
    status: "active",
    visits: 42,
    points: 2480,
    lifetimeSpend: "$1,248.50",
    lastVisit: "Today, 10:42 AM",
    memberSince: "20/06/2024",
    favorite: "S-Bubble Oolong Tea",
  },
  {
    id: "dara-sok",
    customerCode: "C002",
    name: "Dara Sok",
    initials: "DS",
    phone: "+855 97 222 481",
    email: "dara.sok@gmail.com",
    gender: "Male",
    dateOfBirth: "14/05/1992",
    tier: "gold",
    payLater: "$0.00",
    payLaterLimit: "$100.00",
    joinedDate: "12/03/2024",
    tags: ["Regular", "Coffee Lover"],
    status: "active",
    visits: 28,
    points: 1360,
    lifetimeSpend: "$786.00",
    lastVisit: "Yesterday, 4:18 PM",
    memberSince: "Mar 2024",
    favorite: "M-Black Tea Macchiato",
  },
  {
    id: "mony-ly",
    customerCode: "C003",
    name: "Mony Ly",
    initials: "ML",
    phone: "+855 10 678 912",
    email: "mony.ly@gmail.com",
    gender: "Female",
    dateOfBirth: "22/09/1998",
    tier: "member",
    payLater: "$0.00",
    payLaterLimit: "$50.00",
    joinedDate: "05/06/2024",
    tags: ["Student"],
    status: "active",
    visits: 16,
    points: 720,
    lifetimeSpend: "$412.50",
    lastVisit: "Yesterday, 11:06 AM",
    memberSince: "Jun 2024",
    favorite: "Matcha Latte",
  },
  {
    id: "sreypov-kim",
    customerCode: "C004",
    name: "Sreypov Kim",
    initials: "SK",
    phone: "+855 96 435 220",
    email: "sreypov.kim@gmail.com",
    gender: "Female",
    dateOfBirth: "08/11/1995",
    tier: "gold",
    payLater: "$12.00",
    payLaterLimit: "$150.00",
    joinedDate: "18/02/2024",
    tags: ["Loyal", "Office Neighbor"],
    status: "active",
    visits: 24,
    points: 1120,
    lifetimeSpend: "$655.75",
    lastVisit: "Mon, 2:35 PM",
    memberSince: "Feb 2024",
    favorite: "Taro Milk Tea",
  },
  {
    id: "vannak-chea",
    customerCode: "C005",
    name: "Vannak Chea",
    initials: "VC",
    phone: "+855 11 540 709",
    email: "vannak.chea@gmail.com",
    gender: "Male",
    dateOfBirth: "30/07/1990",
    tier: "member",
    payLater: "$0.00",
    payLaterLimit: "$50.00",
    joinedDate: "22/08/2024",
    tags: ["New Member"],
    status: "active",
    visits: 8,
    points: 300,
    lifetimeSpend: "$198.00",
    lastVisit: "Sun, 9:12 AM",
    memberSince: "Aug 2024",
    favorite: "Passion Fruit Tea",
  },
  {
    id: "bopha-chan",
    customerCode: "C006",
    name: "Bopha Chan",
    initials: "BC",
    phone: "+855 12 334 556",
    email: "bopha.chan@gmail.com",
    gender: "Female",
    dateOfBirth: "19/04/1993",
    tier: "vip",
    payLater: "$0.00",
    payLaterLimit: "$300.00",
    joinedDate: "10/01/2024",
    tags: ["VIP", "Corporate"],
    status: "active",
    visits: 56,
    points: 3420,
    lifetimeSpend: "$1,890.00",
    lastVisit: "Today, 08:30 AM",
    memberSince: "Jan 2024",
    favorite: "Brown Sugar Boba Fresh Milk",
  },
  {
    id: "rithy-heng",
    customerCode: "C007",
    name: "Rithy Heng",
    initials: "RH",
    phone: "+855 77 890 123",
    email: "rithy.heng@gmail.com",
    gender: "Male",
    dateOfBirth: "03/12/1988",
    tier: "black",
    payLater: "$35.00",
    payLaterLimit: "$500.00",
    joinedDate: "15/11/2023",
    tags: ["Black Member", "High Value"],
    status: "active",
    visits: 68,
    points: 4890,
    lifetimeSpend: "$2,450.00",
    lastVisit: "Today, 11:15 AM",
    memberSince: "Nov 2023",
    favorite: "Signature Iced Americano",
  },
  {
    id: "vicheka-ou",
    customerCode: "C008",
    name: "Vicheka Ou",
    initials: "VO",
    phone: "+855 81 223 344",
    email: "vicheka.ou@gmail.com",
    gender: "Female",
    dateOfBirth: "27/08/1996",
    tier: "vip",
    payLater: "$0.00",
    payLaterLimit: "$200.00",
    joinedDate: "02/02/2024",
    tags: ["VIP", "Daily Drinker"],
    status: "active",
    visits: 45,
    points: 2750,
    lifetimeSpend: "$1,320.00",
    lastVisit: "Yesterday, 02:45 PM",
    memberSince: "Feb 2024",
    favorite: "Cheese Foam Peach Oolong",
  },
  {
    id: "kosal-sem",
    customerCode: "C009",
    name: "Kosal Sem",
    initials: "KS",
    phone: "+855 89 445 566",
    email: "kosal.sem@gmail.com",
    gender: "Male",
    dateOfBirth: "11/06/1985",
    tier: "gold",
    payLater: "$0.00",
    payLaterLimit: "$150.00",
    joinedDate: "14/04/2024",
    tags: ["Loyal"],
    status: "active",
    visits: 31,
    points: 1580,
    lifetimeSpend: "$890.25",
    lastVisit: "Yesterday, 09:10 AM",
    memberSince: "Apr 2024",
    favorite: "Coconut Cold Brew",
  },
  {
    id: "channa-meas",
    customerCode: "C010",
    name: "Channa Meas",
    initials: "CM",
    phone: "+855 93 556 677",
    email: "channa.meas@gmail.com",
    gender: "Female",
    dateOfBirth: "05/01/1999",
    tier: "member",
    payLater: "$0.00",
    payLaterLimit: "$50.00",
    joinedDate: "19/07/2024",
    tags: ["Student", "Oat Milk"],
    status: "active",
    visits: 12,
    points: 540,
    lifetimeSpend: "$285.50",
    lastVisit: "Today, 01:20 PM",
    memberSince: "Jul 2024",
    favorite: "Oat Milk Caramel Latte",
  },
  {
    id: "sophea-khun",
    customerCode: "C011",
    name: "Sophea Khun",
    initials: "SK",
    phone: "+855 15 667 788",
    email: "sophea.khun@gmail.com",
    gender: "Female",
    dateOfBirth: "16/10/1991",
    tier: "vip",
    payLater: "$18.50",
    payLaterLimit: "$250.00",
    joinedDate: "08/12/2023",
    tags: ["VIP", "Office Neighbor"],
    status: "active",
    visits: 50,
    points: 3100,
    lifetimeSpend: "$1,580.00",
    lastVisit: "Today, 12:05 PM",
    memberSince: "Dec 2023",
    favorite: "Avocado Coffee Frappe",
  },
  {
    id: "sovann-pen",
    customerCode: "C012",
    name: "Sovann Pen",
    initials: "SP",
    phone: "+855 78 778 899",
    email: "sovann.pen@gmail.com",
    gender: "Male",
    dateOfBirth: "25/03/1987",
    tier: "gold",
    payLater: "$0.00",
    payLaterLimit: "$100.00",
    joinedDate: "29/03/2024",
    tags: ["Regular"],
    status: "active",
    visits: 22,
    points: 1050,
    lifetimeSpend: "$620.00",
    lastVisit: "Mon, 10:15 AM",
    memberSince: "Mar 2024",
    favorite: "Jasmine Green Tea Macchiato",
  },
  {
    id: "kagna-yorn",
    customerCode: "C013",
    name: "Kagna Yorn",
    initials: "KY",
    phone: "+855 69 889 900",
    email: "kagna.yorn@gmail.com",
    gender: "Female",
    dateOfBirth: "12/07/1997",
    tier: "member",
    payLater: "$0.00",
    payLaterLimit: "$50.00",
    joinedDate: "14/08/2024",
    tags: ["Afternoon Tea"],
    status: "active",
    visits: 9,
    points: 380,
    lifetimeSpend: "$215.00",
    lastVisit: "Yesterday, 03:30 PM",
    memberSince: "Aug 2024",
    favorite: "Strawberry Lemonade Cooler",
  },
  {
    id: "piseth-chhay",
    customerCode: "C014",
    name: "Piseth Chhay",
    initials: "PC",
    phone: "+855 86 990 011",
    email: "piseth.chhay@gmail.com",
    gender: "Male",
    dateOfBirth: "09/09/1994",
    tier: "vip",
    payLater: "$0.00",
    payLaterLimit: "$200.00",
    joinedDate: "20/01/2024",
    tags: ["VIP", "Tech Hub"],
    status: "active",
    visits: 39,
    points: 2350,
    lifetimeSpend: "$1,150.00",
    lastVisit: "Today, 09:45 AM",
    memberSince: "Jan 2024",
    favorite: "Spanish Latte",
  },
  {
    id: "alexandra-chen",
    customerCode: "C015",
    name: "Alexandra Chen",
    initials: "AC",
    phone: "+855 92 112 233",
    email: "alexandra.chen@gmail.com",
    gender: "Female",
    dateOfBirth: "18/02/1992",
    tier: "black",
    payLater: "$0.00",
    payLaterLimit: "$500.00",
    joinedDate: "05/10/2023",
    tags: ["Black Member", "Expat Community"],
    status: "active",
    visits: 75,
    points: 5200,
    lifetimeSpend: "$2,890.00",
    lastVisit: "Today, 08:15 AM",
    memberSince: "Oct 2023",
    favorite: "Flat White with Almond Milk",
  },
  {
    id: "david-miller",
    customerCode: "C016",
    name: "David Miller",
    initials: "DM",
    phone: "+855 95 223 344",
    email: "david.miller@gmail.com",
    gender: "Male",
    dateOfBirth: "04/08/1982",
    tier: "gold",
    payLater: "$8.00",
    payLaterLimit: "$150.00",
    joinedDate: "17/04/2024",
    tags: ["Daily Espresso"],
    status: "active",
    visits: 27,
    points: 1290,
    lifetimeSpend: "$740.50",
    lastVisit: "Yesterday, 08:00 AM",
    memberSince: "Apr 2024",
    favorite: "Double Espresso",
  },
  {
    id: "sreyneang-ros",
    customerCode: "C017",
    name: "Sreyneang Ros",
    initials: "SR",
    phone: "+855 70 334 455",
    email: "sreyneang.ros@gmail.com",
    gender: "Female",
    dateOfBirth: "29/12/2000",
    tier: "member",
    payLater: "$0.00",
    payLaterLimit: "$50.00",
    joinedDate: "01/09/2024",
    tags: ["Student", "Weekend Regular"],
    status: "active",
    visits: 6,
    points: 240,
    lifetimeSpend: "$145.00",
    lastVisit: "2 days ago",
    memberSince: "Sep 2024",
    favorite: "Honey Lemon Green Tea",
  },
  {
    id: "chamroeun-kong",
    customerCode: "C018",
    name: "Chamroeun Kong",
    initials: "CK",
    phone: "+855 88 445 566",
    email: "chamroeun.kong@gmail.com",
    gender: "Male",
    dateOfBirth: "15/05/1986",
    tier: "vip",
    payLater: "$0.00",
    payLaterLimit: "$250.00",
    joinedDate: "11/11/2023",
    tags: ["VIP", "Corporate Partner"],
    status: "active",
    visits: 48,
    points: 2980,
    lifetimeSpend: "$1,460.00",
    lastVisit: "Today, 02:10 PM",
    memberSince: "Nov 2023",
    favorite: "Roasted Oolong Milk Tea",
  },
  {
    id: "makara-thou",
    customerCode: "C019",
    name: "Makara Thou",
    initials: "MT",
    phone: "+855 16 556 677",
    email: "makara.thou@gmail.com",
    gender: "Male",
    dateOfBirth: "07/01/1993",
    tier: "member",
    payLater: "$0.00",
    payLaterLimit: "$50.00",
    joinedDate: "25/07/2024",
    tags: ["Regular"],
    status: "active",
    visits: 11,
    points: 460,
    lifetimeSpend: "$260.00",
    lastVisit: "3 days ago",
    memberSince: "Jul 2024",
    favorite: "Classic Milk Tea with Pearls",
  },
  {
    id: "chenda-ouk",
    customerCode: "C020",
    name: "Chenda Ouk",
    initials: "CO",
    phone: "+855 98 667 788",
    email: "chenda.ouk@gmail.com",
    gender: "Female",
    dateOfBirth: "21/06/1995",
    tier: "gold",
    payLater: "$0.00",
    payLaterLimit: "$100.00",
    joinedDate: "15/03/2024",
    tags: ["Gold Member"],
    status: "active",
    visits: 25,
    points: 1200,
    lifetimeSpend: "$690.00",
    lastVisit: "Yesterday, 05:20 PM",
    memberSince: "Mar 2024",
    favorite: "Mango Sago Slush",
  },
  {
    id: "panha-sam",
    customerCode: "C021",
    name: "Panha Sam",
    initials: "PS",
    phone: "+855 71 778 899",
    email: "panha.sam@gmail.com",
    gender: "Male",
    dateOfBirth: "10/03/1991",
    tier: "vip",
    payLater: "$22.00",
    payLaterLimit: "$300.00",
    joinedDate: "03/01/2024",
    tags: ["VIP", "Banker"],
    status: "active",
    visits: 52,
    points: 3250,
    lifetimeSpend: "$1,620.00",
    lastVisit: "Today, 11:50 AM",
    memberSince: "Jan 2024",
    favorite: "Sea Salt Caramel Iced Latte",
  },
  {
    id: "kunthea-phou",
    customerCode: "C022",
    name: "Kunthea Phou",
    initials: "KP",
    phone: "+855 85 889 900",
    email: "kunthea.phou@gmail.com",
    gender: "Female",
    dateOfBirth: "14/09/1998",
    tier: "member",
    payLater: "$0.00",
    payLaterLimit: "$50.00",
    joinedDate: "10/08/2024",
    tags: ["New Member"],
    status: "active",
    visits: 5,
    points: 190,
    lifetimeSpend: "$112.50",
    lastVisit: "4 days ago",
    memberSince: "Aug 2024",
    favorite: "Lychee Rose Sparkler",
  },
  {
    id: "visal-noy",
    customerCode: "C023",
    name: "Visal Noy",
    initials: "VN",
    phone: "+855 90 990 011",
    email: "visal.noy@gmail.com",
    gender: "Male",
    dateOfBirth: "28/11/1989",
    tier: "gold",
    payLater: "$0.00",
    payLaterLimit: "$120.00",
    joinedDate: "22/02/2024",
    tags: ["Loyal"],
    status: "active",
    visits: 29,
    points: 1410,
    lifetimeSpend: "$795.00",
    lastVisit: "Yesterday, 01:45 PM",
    memberSince: "Feb 2024",
    favorite: "Dark Chocolate Mocha",
  },
  {
    id: "bormey-keo",
    customerCode: "C024",
    name: "Bormey Keo",
    initials: "BK",
    phone: "+855 17 112 233",
    email: "bormey.keo@gmail.com",
    gender: "Female",
    dateOfBirth: "06/04/1996",
    tier: "vip",
    payLater: "$0.00",
    payLaterLimit: "$200.00",
    joinedDate: "18/12/2023",
    tags: ["VIP", "Influencer"],
    status: "active",
    visits: 43,
    points: 2600,
    lifetimeSpend: "$1,280.00",
    lastVisit: "Today, 03:15 PM",
    memberSince: "Dec 2023",
    favorite: "Uji Matcha Cloud Latte",
  },
  {
    id: "thida-yun",
    customerCode: "C025",
    name: "Thida Yun",
    initials: "TY",
    phone: "+855 60 223 344",
    email: "thida.yun@gmail.com",
    gender: "Female",
    dateOfBirth: "30/10/1994",
    tier: "member",
    payLater: "$0.00",
    payLaterLimit: "$50.00",
    joinedDate: "05/09/2024",
    tags: ["Weekend Regular"],
    status: "active",
    visits: 7,
    points: 280,
    lifetimeSpend: "$160.00",
    lastVisit: "5 days ago",
    memberSince: "Sep 2024",
    favorite: "Kumquat Lemon Tea",
  },
  {
    id: "samnang-lor",
    customerCode: "C026",
    name: "Samnang Lor",
    initials: "SL",
    phone: "+855 79 334 455",
    email: "samnang.lor@gmail.com",
    gender: "Male",
    dateOfBirth: "12/08/1983",
    tier: "black",
    payLater: "$0.00",
    payLaterLimit: "$500.00",
    joinedDate: "01/10/2023",
    tags: ["Black Member", "Investor"],
    status: "active",
    visits: 71,
    points: 5100,
    lifetimeSpend: "$2,650.00",
    lastVisit: "Yesterday, 10:30 AM",
    memberSince: "Oct 2023",
    favorite: "Geisha Pour Over Coffee",
  },
  {
    id: "reaksmey-choun",
    customerCode: "C027",
    name: "Reaksmey Choun",
    initials: "RC",
    phone: "+855 87 445 566",
    email: "reaksmey.choun@gmail.com",
    gender: "Female",
    dateOfBirth: "17/03/1997",
    tier: "gold",
    payLater: "$15.00",
    payLaterLimit: "$150.00",
    joinedDate: "09/04/2024",
    tags: ["Gold Member", "Design Studio"],
    status: "active",
    visits: 26,
    points: 1180,
    lifetimeSpend: "$675.00",
    lastVisit: "Mon, 04:10 PM",
    memberSince: "Apr 2024",
    favorite: "Earl Grey Milk Tea with Pudding",
  },
  {
    id: "virak-son",
    customerCode: "C028",
    name: "Virak Son",
    initials: "VS",
    phone: "+855 99 556 677",
    email: "virak.son@gmail.com",
    gender: "Male",
    dateOfBirth: "23/05/1990",
    tier: "member",
    payLater: "$0.00",
    payLaterLimit: "$50.00",
    joinedDate: "18/06/2024",
    tags: ["Fitness Regular", "No Sugar"],
    status: "active",
    visits: 14,
    points: 590,
    lifetimeSpend: "$320.00",
    lastVisit: "Yesterday, 07:45 AM",
    memberSince: "Jun 2024",
    favorite: "Whey Protein Cold Brew",
  },
  {
    id: "emily-watson",
    customerCode: "C029",
    name: "Emily Watson",
    initials: "EW",
    phone: "+855 93 667 788",
    email: "emily.watson@gmail.com",
    gender: "Female",
    dateOfBirth: "11/12/1987",
    tier: "vip",
    payLater: "$0.00",
    payLaterLimit: "$250.00",
    joinedDate: "14/01/2024",
    tags: ["VIP", "Embassy Staff"],
    status: "active",
    visits: 47,
    points: 2890,
    lifetimeSpend: "$1,410.00",
    lastVisit: "Today, 01:00 PM",
    memberSince: "Jan 2024",
    favorite: "Cortado with Oat Milk",
  },
  {
    id: "seyha-tang",
    customerCode: "C030",
    name: "Seyha Tang",
    initials: "ST",
    phone: "+855 12 778 899",
    email: "seyha.tang@gmail.com",
    gender: "Male",
    dateOfBirth: "08/02/1995",
    tier: "gold",
    payLater: "$0.00",
    payLaterLimit: "$100.00",
    joinedDate: "27/03/2024",
    tags: ["Gold Member"],
    status: "active",
    visits: 23,
    points: 1080,
    lifetimeSpend: "$615.00",
    lastVisit: "Sun, 03:20 PM",
    memberSince: "Mar 2024",
    favorite: "Grapefruit Jasmine Green Tea",
  },
  {
    id: "monica-bellucci",
    customerCode: "C031",
    name: "Monica Bellucci",
    initials: "MB",
    phone: "+855 91 889 900",
    email: "monica.bellucci@gmail.com",
    gender: "Female",
    dateOfBirth: "30/09/1964",
    tier: "black",
    payLater: "$45.00",
    payLaterLimit: "$500.00",
    joinedDate: "15/09/2023",
    tags: ["Black Member", "VIP Exclusive"],
    status: "active",
    visits: 82,
    points: 6100,
    lifetimeSpend: "$3,200.00",
    lastVisit: "Today, 11:30 AM",
    memberSince: "Sep 2023",
    favorite: "Truffle Mocha Macchiato",
  },
  {
    id: "veasna-chhim",
    customerCode: "C032",
    name: "Veasna Chhim",
    initials: "VC",
    phone: "+855 84 990 011",
    email: "veasna.chhim@gmail.com",
    gender: "Male",
    dateOfBirth: "19/06/1993",
    tier: "member",
    payLater: "$0.00",
    payLaterLimit: "$50.00",
    joinedDate: "12/08/2024",
    tags: ["New Member"],
    status: "active",
    visits: 4,
    points: 150,
    lifetimeSpend: "$92.00",
    lastVisit: "Last week",
    memberSince: "Aug 2024",
    favorite: "Wintermelon Lemonade",
  },
  {
    id: "kolap-leng",
    customerCode: "C033",
    name: "Kolap Leng",
    initials: "KL",
    phone: "+855 76 112 233",
    email: "kolap.leng@gmail.com",
    gender: "Female",
    dateOfBirth: "02/05/1992",
    tier: "gold",
    payLater: "$0.00",
    payLaterLimit: "$100.00",
    joinedDate: "04/05/2024",
    tags: ["Gold Member", "Healthcare Staff"],
    status: "active",
    visits: 21,
    points: 990,
    lifetimeSpend: "$570.00",
    lastVisit: "Yesterday, 06:15 PM",
    memberSince: "May 2024",
    favorite: "Grass Jelly Herbal Tea",
  },
  {
    id: "phirun-san",
    customerCode: "C034",
    name: "Phirun San",
    initials: "PS",
    phone: "+855 97 223 344",
    email: "phirun.san@gmail.com",
    gender: "Male",
    dateOfBirth: "14/01/1988",
    tier: "vip",
    payLater: "$0.00",
    payLaterLimit: "$200.00",
    joinedDate: "22/01/2024",
    tags: ["VIP", "Real Estate"],
    status: "active",
    visits: 38,
    points: 2240,
    lifetimeSpend: "$1,110.00",
    lastVisit: "Today, 04:00 PM",
    memberSince: "Jan 2024",
    favorite: "Brown Sugar Caffe Latte",
  },
  {
    id: "dane-prum",
    customerCode: "C035",
    name: "Dane Prum",
    initials: "DP",
    phone: "+855 10 334 455",
    email: "dane.prum@gmail.com",
    gender: "Female",
    dateOfBirth: "25/11/1999",
    tier: "member",
    payLater: "$0.00",
    payLaterLimit: "$50.00",
    joinedDate: "28/08/2024",
    tags: ["Student", "Sweet Tooth"],
    status: "active",
    visits: 10,
    points: 420,
    lifetimeSpend: "$235.00",
    lastVisit: "Mon, 12:40 PM",
    memberSince: "Aug 2024",
    favorite: "Brown Sugar Boba Sundae",
  },
];
