export type DishStatus = "pending" | "completed" | "cancelled";
export type ServiceType = "dineIn" | "takeaway" | "delivery";
export type TicketPriority = "normal" | "rush" | "vip";
export type DishCourse = "Appetizer" | "Main" | "Soup" | "Side" | "Dessert";
export type KitchenStation =
  | "Wok & Grill"
  | "Curry & Simmer"
  | "Steam & Stew"
  | "Fryer"
  | "Soup Station"
  | "Cold & Salad"
  | "Dessert Station";

export interface KitchenDish {
  id: string;
  title: string;
  quantity: number;
  modifiers: string[];
  image: string;
  status: DishStatus;
  course?: DishCourse;
  station?: KitchenStation;
}

export interface KitchenTicket {
  id: string;
  orderCode: string;
  tableNumber: string;
  elapsedSeconds: number;
  serviceType?: ServiceType;
  channel?: string;
  priority?: TicketPriority;
  serverName?: string;
  guestCount?: number;
  notes?: string;
  dishes: KitchenDish[];
}

export const kitchenTickets: KitchenTicket[] = [
  {
    id: "ticket-1082",
    orderCode: "ORD-1082",
    tableNumber: "Table 02/05",
    elapsedSeconds: 14 * 60 + 42,
    serviceType: "dineIn",
    priority: "normal",
    serverName: "Sophea K.",
    guestCount: 4,
    notes: "Peanut allergy alert on table (Guest 3). Separate prep area.",
    dishes: [
      {
        id: "lok-lak-1082",
        title: "Beef Lok Lak",
        quantity: 1,
        modifiers: ["Medium rare", "Pepper-lime sauce on the side"],
        image: "/kitchen/lok-lak.jpg",
        status: "completed",
        course: "Main",
        station: "Wok & Grill",
      },
      {
        id: "curry-1082",
        title: "Khmer Chicken Curry",
        quantity: 2,
        modifiers: ["Mild spice", "Steamed jasmine rice on the side"],
        image: "/kitchen/chicken-curry.jpg",
        status: "completed",
        course: "Main",
        station: "Curry & Simmer",
      },
      {
        id: "spring-rolls-1082",
        title: "Crispy Spring Rolls",
        quantity: 1,
        modifiers: ["Extra herbs", "Sweet chili sauce on the side"],
        image: "/kitchen/spring-rolls.jpg",
        status: "completed",
        course: "Appetizer",
        station: "Fryer",
      },
      {
        id: "mango-sticky-rice-1082",
        title: "Mango Sticky Rice",
        quantity: 1,
        modifiers: ["Coconut cream on the side", "No sesame seeds"],
        image: "/kitchen/mango-sticky-rice.jpg",
        status: "pending",
        course: "Dessert",
        station: "Dessert Station",
      },
    ],
  },
  {
    id: "ticket-1086",
    orderCode: "ORD-1086",
    tableNumber: "Table 08/05",
    elapsedSeconds: 18 * 60 + 16,
    serviceType: "dineIn",
    priority: "rush",
    serverName: "Dara M.",
    guestCount: 2,
    notes: "Rush order: Guests have movie reservation in 30 mins.",
    dishes: [
      {
        id: "skewers-1086",
        title: "Lemongrass Beef Skewers",
        quantity: 2,
        modifiers: ["Pickled papaya on side", "Spicy tamarind sauce"],
        image: "/products/product-2.png",
        status: "completed",
        course: "Appetizer",
        station: "Wok & Grill",
      },
      {
        id: "lok-lak-1086",
        title: "Beef Lok Lak",
        quantity: 1,
        modifiers: ["Well done", "Extra pepper-lime sauce"],
        image: "/kitchen/lok-lak.jpg",
        status: "pending",
        course: "Main",
        station: "Wok & Grill",
      },
      {
        id: "spring-rolls-1086",
        title: "Crispy Spring Rolls",
        quantity: 2,
        modifiers: ["Chili sauce on the side"],
        image: "/kitchen/spring-rolls.jpg",
        status: "completed",
        course: "Appetizer",
        station: "Fryer",
      },
      {
        id: "curry-1086",
        title: "Khmer Chicken Curry",
        quantity: 1,
        modifiers: ["Extra mild", "Warm baguette instead of rice"],
        image: "/kitchen/chicken-curry.jpg",
        status: "pending",
        course: "Main",
        station: "Curry & Simmer",
      },
    ],
  },
  {
    id: "ticket-1088",
    orderCode: "ORD-1088",
    tableNumber: "Table 04/05",
    elapsedSeconds: 5 * 60 + 29,
    serviceType: "dineIn",
    priority: "normal",
    serverName: "Vibol N.",
    guestCount: 3,
    dishes: [
      {
        id: "amok-1088",
        title: "Traditional Fish Amok",
        quantity: 2,
        modifiers: ["Steamed in banana leaf", "Mild kroeung spice", "Jasmine rice"],
        image: "/products/product-1.png",
        status: "pending",
        course: "Main",
        station: "Steam & Stew",
      },
      {
        id: "mango-sticky-rice-1088",
        title: "Mango Sticky Rice",
        quantity: 1,
        modifiers: ["Warm coconut cream on the side"],
        image: "/kitchen/mango-sticky-rice.jpg",
        status: "pending",
        course: "Dessert",
        station: "Dessert Station",
      },
      {
        id: "lok-lak-1088",
        title: "Beef Lok Lak",
        quantity: 2,
        modifiers: ["Medium", "No fried egg", "Extra crisp salad"],
        image: "/kitchen/lok-lak.jpg",
        status: "pending",
        course: "Main",
        station: "Wok & Grill",
      },
    ],
  },
  {
    id: "ticket-1089",
    orderCode: "ORD-1089",
    tableNumber: "Table 01/05",
    elapsedSeconds: 24 * 60 + 35,
    serviceType: "dineIn",
    priority: "vip",
    serverName: "Chanthy V.",
    guestCount: 6,
    notes: "VIP table: 10th Wedding Anniversary. Present dishes with ceremony.",
    dishes: [
      {
        id: "lok-lak-1089",
        title: "Beef Lok Lak",
        quantity: 2,
        modifiers: ["Medium rare", "Extra fried eggs", "Kampot green peppercorns"],
        image: "/kitchen/lok-lak.jpg",
        status: "completed",
        course: "Main",
        station: "Wok & Grill",
      },
      {
        id: "curry-1089",
        title: "Khmer Chicken Curry",
        quantity: 2,
        modifiers: ["Medium spice", "Extra jasmine rice"],
        image: "/kitchen/chicken-curry.jpg",
        status: "completed",
        course: "Main",
        station: "Curry & Simmer",
      },
      {
        id: "spring-rolls-1089",
        title: "Crispy Spring Rolls",
        quantity: 3,
        modifiers: ["No cilantro", "Sweet chili sauce on side"],
        image: "/kitchen/spring-rolls.jpg",
        status: "completed",
        course: "Appetizer",
        station: "Fryer",
      },
      {
        id: "seafood-rice-1089",
        title: "Wok Seafood Fried Rice",
        quantity: 2,
        modifiers: ["Extra tiger prawns", "Spicy garlic fish sauce"],
        image: "/products/product-3.png",
        status: "pending",
        course: "Main",
        station: "Wok & Grill",
      },
    ],
  },
  {
    id: "ticket-1090",
    orderCode: "ORD-1090",
    tableNumber: "Table 03/05",
    elapsedSeconds: 20 * 60 + 12,
    serviceType: "dineIn",
    priority: "normal",
    serverName: "Bopha S.",
    guestCount: 2,
    dishes: [
      {
        id: "tomyum-1090",
        title: "Tom Yum Seafood Soup",
        quantity: 1,
        modifiers: ["Medium spice", "Extra lemongrass & galangal"],
        image: "/products/product-5.png",
        status: "completed",
        course: "Soup",
        station: "Soup Station",
      },
      {
        id: "curry-1090",
        title: "Khmer Chicken Curry",
        quantity: 2,
        modifiers: ["Extra spicy", "No potatoes"],
        image: "/kitchen/chicken-curry.jpg",
        status: "completed",
        course: "Main",
        station: "Curry & Simmer",
      },
      {
        id: "mango-sticky-rice-1090",
        title: "Mango Sticky Rice",
        quantity: 2,
        modifiers: ["Extra coconut cream", "Extra ripe mango"],
        image: "/kitchen/mango-sticky-rice.jpg",
        status: "pending",
        course: "Dessert",
        station: "Dessert Station",
      },
      {
        id: "lok-lak-1090",
        title: "Beef Lok Lak",
        quantity: 1,
        modifiers: ["Well done", "No raw onion"],
        image: "/kitchen/lok-lak.jpg",
        status: "pending",
        course: "Main",
        station: "Wok & Grill",
      },
    ],
  },
  {
    id: "ticket-1091",
    orderCode: "ORD-1091",
    tableNumber: "Table 06/05",
    elapsedSeconds: 17 * 60 + 48,
    serviceType: "dineIn",
    priority: "normal",
    serverName: "Sophea K.",
    guestCount: 4,
    dishes: [
      {
        id: "spring-rolls-1091",
        title: "Crispy Spring Rolls",
        quantity: 2,
        modifiers: ["Extra fresh vegetables", "Peanut sauce on side"],
        image: "/kitchen/spring-rolls.jpg",
        status: "completed",
        course: "Appetizer",
        station: "Fryer",
      },
      {
        id: "lok-lak-1091",
        title: "Beef Lok Lak",
        quantity: 3,
        modifiers: ["Medium", "Pepper-lime sauce on the side"],
        image: "/kitchen/lok-lak.jpg",
        status: "completed",
        course: "Main",
        station: "Wok & Grill",
      },
      {
        id: "amok-1091",
        title: "Traditional Fish Amok",
        quantity: 1,
        modifiers: ["Mild spice", "Steamed in banana leaf"],
        image: "/products/product-1.png",
        status: "pending",
        course: "Main",
        station: "Steam & Stew",
      },
      {
        id: "mango-sticky-rice-1091",
        title: "Mango Sticky Rice",
        quantity: 1,
        modifiers: ["No sesame"],
        image: "/kitchen/mango-sticky-rice.jpg",
        status: "pending",
        course: "Dessert",
        station: "Dessert Station",
      },
    ],
  },
  {
    id: "ticket-1092",
    orderCode: "ORD-1092",
    tableNumber: "Table 09/05",
    elapsedSeconds: 15 * 60 + 21,
    serviceType: "dineIn",
    priority: "normal",
    serverName: "Rithy C.",
    guestCount: 2,
    dishes: [
      {
        id: "papaya-1092",
        title: "Bok Lhong Papaya Salad",
        quantity: 1,
        modifiers: ["2 chilies (Mild)", "Dried shrimp", "Peanuts on side"],
        image: "/products/product-6.png",
        status: "completed",
        course: "Appetizer",
        station: "Cold & Salad",
      },
      {
        id: "lok-lak-1092",
        title: "Beef Lok Lak",
        quantity: 2,
        modifiers: ["Medium well", "Extra fresh vegetables"],
        image: "/kitchen/lok-lak.jpg",
        status: "completed",
        course: "Main",
        station: "Wok & Grill",
      },
      {
        id: "spring-rolls-1092",
        title: "Crispy Spring Rolls",
        quantity: 1,
        modifiers: ["No chili", "Extra dipping sweet sauce"],
        image: "/kitchen/spring-rolls.jpg",
        status: "completed",
        course: "Appetizer",
        station: "Fryer",
      },
      {
        id: "mango-sticky-rice-1092",
        title: "Mango Sticky Rice",
        quantity: 2,
        modifiers: ["Extra mango", "Coconut cream on the side"],
        image: "/kitchen/mango-sticky-rice.jpg",
        status: "pending",
        course: "Dessert",
        station: "Dessert Station",
      },
    ],
  },
  {
    id: "ticket-1093",
    orderCode: "ORD-1093",
    tableNumber: "Table 10/05",
    elapsedSeconds: 12 * 60 + 53,
    serviceType: "dineIn",
    priority: "normal",
    serverName: "Dara M.",
    guestCount: 3,
    notes: "Serve curry piping hot with warm crusty baguettes.",
    dishes: [
      {
        id: "curry-1093",
        title: "Khmer Chicken Curry",
        quantity: 3,
        modifiers: ["Medium spice", "Toasted warm baguettes"],
        image: "/kitchen/chicken-curry.jpg",
        status: "pending",
        course: "Main",
        station: "Curry & Simmer",
      },
      {
        id: "morning-glory-1093",
        title: "Stir-Fried Morning Glory",
        quantity: 1,
        modifiers: ["Crispy fried garlic on top", "Less oil"],
        image: "/products/product-7.png",
        status: "completed",
        course: "Side",
        station: "Wok & Grill",
      },
      {
        id: "spring-rolls-1093",
        title: "Crispy Spring Rolls",
        quantity: 2,
        modifiers: ["Extra herbs", "Chili sauce on the side"],
        image: "/kitchen/spring-rolls.jpg",
        status: "completed",
        course: "Appetizer",
        station: "Fryer",
      },
    ],
  },
  {
    id: "ticket-1094",
    orderCode: "ORD-1094",
    tableNumber: "Table 11/05",
    elapsedSeconds: 10 * 60 + 37,
    serviceType: "dineIn",
    priority: "normal",
    serverName: "Vibol N.",
    guestCount: 2,
    dishes: [
      {
        id: "lok-lak-1094",
        title: "Beef Lok Lak",
        quantity: 1,
        modifiers: ["Rare", "No tomato slices", "Extra pepper dip"],
        image: "/kitchen/lok-lak.jpg",
        status: "pending",
        course: "Main",
        station: "Wok & Grill",
      },
      {
        id: "curry-1094",
        title: "Khmer Chicken Curry",
        quantity: 2,
        modifiers: ["Extra spicy", "Steamed jasmine rice"],
        image: "/kitchen/chicken-curry.jpg",
        status: "pending",
        course: "Main",
        station: "Curry & Simmer",
      },
      {
        id: "mango-sticky-rice-1094",
        title: "Mango Sticky Rice",
        quantity: 3,
        modifiers: ["Less sweet syrup", "Extra coconut cream"],
        image: "/kitchen/mango-sticky-rice.jpg",
        status: "pending",
        course: "Dessert",
        station: "Dessert Station",
      },
    ],
  },
  {
    id: "ticket-1095",
    orderCode: "ORD-1095",
    tableNumber: "Table 12/05",
    elapsedSeconds: 8 * 60 + 24,
    serviceType: "dineIn",
    priority: "normal",
    serverName: "Chanthy V.",
    guestCount: 5,
    dishes: [
      {
        id: "spring-rolls-1095",
        title: "Crispy Spring Rolls",
        quantity: 4,
        modifiers: ["Extra crispy", "Sweet chili sauce on side"],
        image: "/kitchen/spring-rolls.jpg",
        status: "completed",
        course: "Appetizer",
        station: "Fryer",
      },
      {
        id: "pork-belly-1095",
        title: "Crispy Five-Spice Pork Belly",
        quantity: 2,
        modifiers: ["Extra crisp crackling", "Hoisin mustard dip"],
        image: "/products/product-4.png",
        status: "pending",
        course: "Main",
        station: "Fryer",
      },
      {
        id: "lok-lak-1095",
        title: "Beef Lok Lak",
        quantity: 2,
        modifiers: ["Medium rare", "Extra pepper-lime sauce"],
        image: "/kitchen/lok-lak.jpg",
        status: "pending",
        course: "Main",
        station: "Wok & Grill",
      },
      {
        id: "curry-1095",
        title: "Khmer Chicken Curry",
        quantity: 1,
        modifiers: ["No chili", "Rice on the side"],
        image: "/kitchen/chicken-curry.jpg",
        status: "pending",
        course: "Main",
        station: "Curry & Simmer",
      },
    ],
  },
  {
    id: "ticket-1096",
    orderCode: "ORD-1096",
    tableNumber: "Table 13/05",
    elapsedSeconds: 6 * 60 + 58,
    serviceType: "dineIn",
    priority: "normal",
    serverName: "Sreymom P.",
    guestCount: 2,
    dishes: [
      {
        id: "mango-sticky-rice-1096",
        title: "Mango Sticky Rice",
        quantity: 2,
        modifiers: ["Extra mango", "No sesame seeds"],
        image: "/kitchen/mango-sticky-rice.jpg",
        status: "pending",
        course: "Dessert",
        station: "Dessert Station",
      },
      {
        id: "spring-rolls-1096",
        title: "Crispy Spring Rolls",
        quantity: 1,
        modifiers: ["No peanuts", "Sauce on the side"],
        image: "/kitchen/spring-rolls.jpg",
        status: "pending",
        course: "Appetizer",
        station: "Fryer",
      },
      {
        id: "jelly-1096",
        title: "Coconut Pandan Custard Jelly",
        quantity: 2,
        modifiers: ["Chilled", "Extra coconut drizzle"],
        image: "/products/product-8.png",
        status: "pending",
        course: "Dessert",
        station: "Dessert Station",
      },
    ],
  },
  {
    id: "ticket-1097",
    orderCode: "ORD-1097",
    tableNumber: "Table 14/05",
    elapsedSeconds: 5 * 60 + 32,
    serviceType: "dineIn",
    priority: "normal",
    serverName: "Bopha S.",
    guestCount: 4,
    dishes: [
      {
        id: "lok-lak-1097",
        title: "Beef Lok Lak",
        quantity: 3,
        modifiers: ["Well done", "Extra fried egg on all"],
        image: "/kitchen/lok-lak.jpg",
        status: "pending",
        course: "Main",
        station: "Wok & Grill",
      },
      {
        id: "curry-1097",
        title: "Khmer Chicken Curry",
        quantity: 2,
        modifiers: ["Mild spice", "Extra simmered potatoes"],
        image: "/kitchen/chicken-curry.jpg",
        status: "pending",
        course: "Main",
        station: "Curry & Simmer",
      },
      {
        id: "spring-rolls-1097",
        title: "Crispy Spring Rolls",
        quantity: 2,
        modifiers: ["Vegetarian recipe", "No cilantro"],
        image: "/kitchen/spring-rolls.jpg",
        status: "pending",
        course: "Appetizer",
        station: "Fryer",
      },
    ],
  },
  {
    id: "ticket-1098",
    orderCode: "ORD-1098",
    tableNumber: "Table 15/05",
    elapsedSeconds: 4 * 60 + 17,
    serviceType: "dineIn",
    priority: "normal",
    serverName: "Sophea K.",
    guestCount: 2,
    dishes: [
      {
        id: "curry-1098",
        title: "Khmer Chicken Curry",
        quantity: 1,
        modifiers: ["Extra spicy", "Extra steamed jasmine rice"],
        image: "/kitchen/chicken-curry.jpg",
        status: "pending",
        course: "Main",
        station: "Curry & Simmer",
      },
      {
        id: "mango-sticky-rice-1098",
        title: "Mango Sticky Rice",
        quantity: 2,
        modifiers: ["Warm coconut cream on side"],
        image: "/kitchen/mango-sticky-rice.jpg",
        status: "pending",
        course: "Dessert",
        station: "Dessert Station",
      },
      {
        id: "lok-lak-1098",
        title: "Beef Lok Lak",
        quantity: 1,
        modifiers: ["Medium", "No fried egg"],
        image: "/kitchen/lok-lak.jpg",
        status: "pending",
        course: "Main",
        station: "Wok & Grill",
      },
    ],
  },
  {
    id: "ticket-1099",
    orderCode: "ORD-1099",
    tableNumber: "Table 16/05",
    elapsedSeconds: 3 * 60 + 46,
    serviceType: "dineIn",
    priority: "normal",
    serverName: "Dara M.",
    guestCount: 3,
    dishes: [
      {
        id: "spring-rolls-1099",
        title: "Crispy Spring Rolls",
        quantity: 3,
        modifiers: ["Extra fresh herbs", "Peanut dipping sauce"],
        image: "/kitchen/spring-rolls.jpg",
        status: "pending",
        course: "Appetizer",
        station: "Fryer",
      },
      {
        id: "lok-lak-1099",
        title: "Beef Lok Lak",
        quantity: 2,
        modifiers: ["Medium rare", "No raw onions"],
        image: "/kitchen/lok-lak.jpg",
        status: "pending",
        course: "Main",
        station: "Wok & Grill",
      },
      {
        id: "skewers-1099",
        title: "Lemongrass Beef Skewers",
        quantity: 2,
        modifiers: ["Charred crisp", "Papaya slaw on side"],
        image: "/products/product-2.png",
        status: "pending",
        course: "Appetizer",
        station: "Wok & Grill",
      },
    ],
  },
  {
    id: "ticket-1100",
    orderCode: "ORD-1100",
    tableNumber: "Table 17/05",
    elapsedSeconds: 2 * 60 + 18,
    serviceType: "dineIn",
    priority: "normal",
    serverName: "Vibol N.",
    guestCount: 4,
    dishes: [
      {
        id: "curry-1100",
        title: "Khmer Chicken Curry",
        quantity: 2,
        modifiers: ["Medium spice", "Steamed rice on side"],
        image: "/kitchen/chicken-curry.jpg",
        status: "pending",
        course: "Main",
        station: "Curry & Simmer",
      },
      {
        id: "spring-rolls-1100",
        title: "Crispy Spring Rolls",
        quantity: 2,
        modifiers: ["Extra crispy", "Chili dipping sauce"],
        image: "/kitchen/spring-rolls.jpg",
        status: "pending",
        course: "Appetizer",
        station: "Fryer",
      },
      {
        id: "mango-sticky-rice-1100",
        title: "Mango Sticky Rice",
        quantity: 1,
        modifiers: ["Less sweet sugar syrup"],
        image: "/kitchen/mango-sticky-rice.jpg",
        status: "pending",
        course: "Dessert",
        station: "Dessert Station",
      },
    ],
  },
  {
    id: "ticket-1101",
    orderCode: "ORD-1101",
    tableNumber: "Bar Counter 02",
    elapsedSeconds: 1 * 60 + 45,
    serviceType: "dineIn",
    priority: "normal",
    serverName: "Rithy C.",
    guestCount: 1,
    notes: "Bar guest ordering finger foods while having draught Angkor beer.",
    dishes: [
      {
        id: "skewers-1101",
        title: "Lemongrass Beef Skewers",
        quantity: 2,
        modifiers: ["Extra charred", "Tamarind chili dip"],
        image: "/products/product-2.png",
        status: "pending",
        course: "Appetizer",
        station: "Wok & Grill",
      },
      {
        id: "spring-rolls-1101",
        title: "Crispy Spring Rolls",
        quantity: 1,
        modifiers: ["Extra crispy", "Sweet chili sauce"],
        image: "/kitchen/spring-rolls.jpg",
        status: "pending",
        course: "Appetizer",
        station: "Fryer",
      },
      {
        id: "morning-glory-1101",
        title: "Stir-Fried Morning Glory",
        quantity: 1,
        modifiers: ["Extra crispy garlic", "Spicy chili paste"],
        image: "/products/product-7.png",
        status: "pending",
        course: "Side",
        station: "Wok & Grill",
      },
    ],
  },
  {
    id: "ticket-1102",
    orderCode: "ORD-1102",
    tableNumber: "VIP Salon 01",
    elapsedSeconds: 27 * 60 + 10,
    serviceType: "dineIn",
    priority: "vip",
    serverName: "Sophea K.",
    guestCount: 8,
    notes: "Ambassador Dinner. Course in 3 rounds: Starters -> Mains -> Desserts.",
    dishes: [
      {
        id: "amok-1102",
        title: "Traditional Fish Amok",
        quantity: 4,
        modifiers: ["Steamed in banana leaf bowls", "Kaffir lime leaf garnish"],
        image: "/products/product-1.png",
        status: "completed",
        course: "Main",
        station: "Steam & Stew",
      },
      {
        id: "lok-lak-1102",
        title: "Beef Lok Lak",
        quantity: 4,
        modifiers: ["Tenderloin cut", "Medium rare", "Kampot pepper dip"],
        image: "/kitchen/lok-lak.jpg",
        status: "completed",
        course: "Main",
        station: "Wok & Grill",
      },
      {
        id: "tomyum-1102",
        title: "Tom Yum Seafood Soup",
        quantity: 2,
        modifiers: ["Jumbo river prawns", "Fragrant lemongrass broth"],
        image: "/products/product-5.png",
        status: "completed",
        course: "Soup",
        station: "Soup Station",
      },
      {
        id: "pork-belly-1102",
        title: "Crispy Five-Spice Pork Belly",
        quantity: 3,
        modifiers: ["Crackling skin", "Steamed lotus buns", "Hoisin glaze"],
        image: "/products/product-4.png",
        status: "pending",
        course: "Main",
        station: "Fryer",
      },
      {
        id: "seafood-rice-1102",
        title: "Wok Seafood Fried Rice",
        quantity: 3,
        modifiers: ["Fresh crab meat", "Tiger prawns", "Scallions"],
        image: "/products/product-3.png",
        status: "pending",
        course: "Main",
        station: "Wok & Grill",
      },
      {
        id: "mango-sticky-rice-1102",
        title: "Mango Sticky Rice",
        quantity: 4,
        modifiers: ["Golden sweet mango", "Warm coconut cream in saucepot"],
        image: "/kitchen/mango-sticky-rice.jpg",
        status: "pending",
        course: "Dessert",
        station: "Dessert Station",
      },
    ],
  },
  {
    id: "ticket-1103",
    orderCode: "ORD-1103",
    tableNumber: "Takeaway #TK-14",
    elapsedSeconds: 7 * 60 + 15,
    serviceType: "takeaway",
    priority: "normal",
    serverName: "Cashier Counter 1",
    notes: "Customer waiting at reception. Double bag all curries & gravies.",
    dishes: [
      {
        id: "lok-lak-1103",
        title: "Beef Lok Lak",
        quantity: 2,
        modifiers: ["Medium well", "Sauce sealed in takeaway container"],
        image: "/kitchen/lok-lak.jpg",
        status: "completed",
        course: "Main",
        station: "Wok & Grill",
      },
      {
        id: "spring-rolls-1103",
        title: "Crispy Spring Rolls",
        quantity: 2,
        modifiers: ["Vented box to maintain crispiness"],
        image: "/kitchen/spring-rolls.jpg",
        status: "completed",
        course: "Appetizer",
        station: "Fryer",
      },
      {
        id: "curry-1103",
        title: "Khmer Chicken Curry",
        quantity: 1,
        modifiers: ["Mild spice", "Separate container for jasmine rice"],
        image: "/kitchen/chicken-curry.jpg",
        status: "pending",
        course: "Main",
        station: "Curry & Simmer",
      },
    ],
  },
  {
    id: "ticket-1104",
    orderCode: "ORD-1104",
    tableNumber: "Foodpanda #FP-482",
    elapsedSeconds: 11 * 60 + 50,
    serviceType: "delivery",
    channel: "Foodpanda",
    priority: "rush",
    notes: "Foodpanda rider #849 already arrived at pick-up door. Expedite!",
    dishes: [
      {
        id: "seafood-rice-1104",
        title: "Wok Seafood Fried Rice",
        quantity: 2,
        modifiers: ["Extra spicy chili packets included"],
        image: "/products/product-3.png",
        status: "completed",
        course: "Main",
        station: "Wok & Grill",
      },
      {
        id: "spring-rolls-1104",
        title: "Crispy Spring Rolls",
        quantity: 1,
        modifiers: ["Sweet chili dipping cup sealed"],
        image: "/kitchen/spring-rolls.jpg",
        status: "completed",
        course: "Appetizer",
        station: "Fryer",
      },
      {
        id: "mango-sticky-rice-1104",
        title: "Mango Sticky Rice",
        quantity: 2,
        modifiers: ["Cold dessert - pack separate from hot rice"],
        image: "/kitchen/mango-sticky-rice.jpg",
        status: "pending",
        course: "Dessert",
        station: "Dessert Station",
      },
    ],
  },
  {
    id: "ticket-1105",
    orderCode: "ORD-1105",
    tableNumber: "Wownow #WN-729",
    elapsedSeconds: 9 * 60 + 12,
    serviceType: "delivery",
    channel: "Wownow",
    priority: "normal",
    notes: "Include chopsticks, napkins, and disposable spoon sets.",
    dishes: [
      {
        id: "amok-1105",
        title: "Traditional Fish Amok",
        quantity: 1,
        modifiers: ["Sealed thermal foil pouch", "Steamed rice box"],
        image: "/products/product-1.png",
        status: "pending",
        course: "Main",
        station: "Steam & Stew",
      },
      {
        id: "lok-lak-1105",
        title: "Beef Lok Lak",
        quantity: 1,
        modifiers: ["Medium rare", "Fried egg on top", "Pepper sauce on side"],
        image: "/kitchen/lok-lak.jpg",
        status: "pending",
        course: "Main",
        station: "Wok & Grill",
      },
      {
        id: "morning-glory-1105",
        title: "Stir-Fried Morning Glory",
        quantity: 1,
        modifiers: ["Garlic oyster sauce", "No MSG"],
        image: "/products/product-7.png",
        status: "pending",
        course: "Side",
        station: "Wok & Grill",
      },
    ],
  },
  {
    id: "ticket-1106",
    orderCode: "ORD-1106",
    tableNumber: "Table 05/Garden",
    elapsedSeconds: 6 * 60 + 33,
    serviceType: "dineIn",
    priority: "normal",
    serverName: "Chanthy V.",
    guestCount: 4,
    dishes: [
      {
        id: "tomyum-1106",
        title: "Tom Yum Seafood Soup",
        quantity: 2,
        modifiers: ["Spicy & sour", "Extra oyster mushrooms"],
        image: "/products/product-5.png",
        status: "pending",
        course: "Soup",
        station: "Soup Station",
      },
      {
        id: "papaya-1106",
        title: "Bok Lhong Papaya Salad",
        quantity: 2,
        modifiers: ["Crispy pork rinds on side", "3 chilies (Spicy)"],
        image: "/products/product-6.png",
        status: "pending",
        course: "Appetizer",
        station: "Cold & Salad",
      },
      {
        id: "pork-belly-1106",
        title: "Crispy Five-Spice Pork Belly",
        quantity: 2,
        modifiers: ["Golden crackling", "Pickled shallots dip"],
        image: "/products/product-4.png",
        status: "pending",
        course: "Main",
        station: "Fryer",
      },
      {
        id: "jelly-1106",
        title: "Coconut Pandan Custard Jelly",
        quantity: 4,
        modifiers: ["Chilled dessert round", "Toasted sesame sprinkles"],
        image: "/products/product-8.png",
        status: "pending",
        course: "Dessert",
        station: "Dessert Station",
      },
    ],
  },
  {
    id: "ticket-1107",
    orderCode: "ORD-1107",
    tableNumber: "GrabFood #GF-319",
    elapsedSeconds: 13 * 60 + 40,
    serviceType: "delivery",
    channel: "GrabFood",
    priority: "normal",
    notes: "Contactless delivery requested. Label all boxes clearly.",
    dishes: [
      {
        id: "curry-1107",
        title: "Khmer Chicken Curry",
        quantity: 2,
        modifiers: ["Mild spice", "Double jasmine rice"],
        image: "/kitchen/chicken-curry.jpg",
        status: "completed",
        course: "Main",
        station: "Curry & Simmer",
      },
      {
        id: "lok-lak-1107",
        title: "Beef Lok Lak",
        quantity: 1,
        modifiers: ["Well done", "Extra pepper lime sauce cup"],
        image: "/kitchen/lok-lak.jpg",
        status: "completed",
        course: "Main",
        station: "Wok & Grill",
      },
      {
        id: "spring-rolls-1107",
        title: "Crispy Spring Rolls",
        quantity: 2,
        modifiers: ["Extra crispy", "Sweet chili dipping cups"],
        image: "/kitchen/spring-rolls.jpg",
        status: "pending",
        course: "Appetizer",
        station: "Fryer",
      },
    ],
  },
  {
    id: "ticket-1108",
    orderCode: "ORD-1108",
    tableNumber: "VIP Salon 02",
    elapsedSeconds: 16 * 60 + 5,
    serviceType: "dineIn",
    priority: "vip",
    serverName: "Sreymom P.",
    guestCount: 6,
    notes: "Birthday party. Bring dessert with candle sparklers after mains.",
    dishes: [
      {
        id: "seafood-rice-1108",
        title: "Wok Seafood Fried Rice",
        quantity: 3,
        modifiers: ["Jumbo crab lumps", "Tiger prawns", "Chili fish sauce"],
        image: "/products/product-3.png",
        status: "completed",
        course: "Main",
        station: "Wok & Grill",
      },
      {
        id: "amok-1108",
        title: "Traditional Fish Amok",
        quantity: 3,
        modifiers: ["Banana leaf bowls", "Rich coconut cream swirl"],
        image: "/products/product-1.png",
        status: "completed",
        course: "Main",
        station: "Steam & Stew",
      },
      {
        id: "skewers-1108",
        title: "Lemongrass Beef Skewers",
        quantity: 4,
        modifiers: ["Charred lemongrass glaze", "Green papaya pickle"],
        image: "/products/product-2.png",
        status: "pending",
        course: "Appetizer",
        station: "Wok & Grill",
      },
      {
        id: "mango-sticky-rice-1108",
        title: "Mango Sticky Rice",
        quantity: 3,
        modifiers: ["Sweet yellow mango", "Warm coconut cream in ramekins"],
        image: "/kitchen/mango-sticky-rice.jpg",
        status: "pending",
        course: "Dessert",
        station: "Dessert Station",
      },
      {
        id: "jelly-1108",
        title: "Coconut Pandan Custard Jelly",
        quantity: 3,
        modifiers: ["Chilled layered custard", "Sesame garnish"],
        image: "/products/product-8.png",
        status: "pending",
        course: "Dessert",
        station: "Dessert Station",
      },
    ],
  },
  {
    id: "ticket-1109",
    orderCode: "ORD-1109",
    tableNumber: "Takeaway #TK-19",
    elapsedSeconds: 4 * 60 + 2,
    serviceType: "takeaway",
    priority: "normal",
    serverName: "Cashier Counter 2",
    notes: "Customer waiting in parking lot.",
    dishes: [
      {
        id: "pork-belly-1109",
        title: "Crispy Five-Spice Pork Belly",
        quantity: 1,
        modifiers: ["Extra crackling", "Double hoisin dip"],
        image: "/products/product-4.png",
        status: "pending",
        course: "Main",
        station: "Fryer",
      },
      {
        id: "papaya-1109",
        title: "Bok Lhong Papaya Salad",
        quantity: 1,
        modifiers: ["1 chili (Very mild)", "Peanuts packed separately"],
        image: "/products/product-6.png",
        status: "pending",
        course: "Appetizer",
        station: "Cold & Salad",
      },
      {
        id: "curry-1109",
        title: "Khmer Chicken Curry",
        quantity: 1,
        modifiers: ["Medium spice", "Fresh French baguette"],
        image: "/kitchen/chicken-curry.jpg",
        status: "pending",
        course: "Main",
        station: "Curry & Simmer",
      },
    ],
  },
  {
    id: "ticket-1110",
    orderCode: "ORD-1110",
    tableNumber: "Nham24 #NH-104",
    elapsedSeconds: 22 * 60 + 40,
    serviceType: "delivery",
    channel: "Nham24",
    priority: "rush",
    notes: "Corporate lunch order for French Embassy. High priority dispatch.",
    dishes: [
      {
        id: "lok-lak-1110",
        title: "Beef Lok Lak",
        quantity: 3,
        modifiers: ["Medium rare", "Fried egg on each", "Pepper sauce on side"],
        image: "/kitchen/lok-lak.jpg",
        status: "completed",
        course: "Main",
        station: "Wok & Grill",
      },
      {
        id: "amok-1110",
        title: "Traditional Fish Amok",
        quantity: 2,
        modifiers: ["Mild aromatic spice", "Fragrant jasmine rice"],
        image: "/products/product-1.png",
        status: "completed",
        course: "Main",
        station: "Steam & Stew",
      },
      {
        id: "spring-rolls-1110",
        title: "Crispy Spring Rolls",
        quantity: 3,
        modifiers: ["Fresh herbs tray", "Sweet chili sauce cups"],
        image: "/kitchen/spring-rolls.jpg",
        status: "pending",
        course: "Appetizer",
        station: "Fryer",
      },
    ],
  },
];
