import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import { Geist_Mono, Inter, Kantumruy_Pro } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({
  display: "swap",
  fallback: ["sans-serif"],
  subsets: ["latin"],
  variable: "--font-inter",
});

const kantumruyPro = Kantumruy_Pro({
  display: "swap",
  fallback: ["Noto Sans Khmer", "sans-serif"],
  subsets: ["khmer", "latin"],
  variable: "--font-kantumruy-pro",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const locale = await getLocale();

  return (
    <html
      lang={locale}
      className={`${inter.variable} ${kantumruyPro.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body
        className="min-h-full flex flex-col bg-background text-foreground font-sans"
        suppressHydrationWarning
      >
        <NextIntlClientProvider>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
